# Generated by Django 3.1b1 on 2020-09-07 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0014_auto_20200907_2307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/home/vladislav/PycharmProjects/django_movie_site/accounts/static/account/img/127889.jpg', upload_to='users/avatars/<function get_hashed_path at 0x7fe44ca08f70>', verbose_name='Avatar')),
                ('favorites', models.ManyToManyField(to='movies.Movies', verbose_name='Favorite movies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
