# Generated by Django 3.1b1 on 2020-09-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20200907_2313'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/home/vladislav/PycharmProjects/django_movie_site/accounts/static/account/img/97365.jpg', upload_to='users/avatars/<function get_hashed_path at 0x7f237d4e4f70>', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='movies.Movies', verbose_name='Favorite movies'),
        ),
    ]
