# Generated by Django 3.1b1 on 2020-09-08 09:45

from django.db import migrations, models
import movies.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200907_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/home/vladislav/PycharmProjects/django_movie_site/accounts/static/account/img/204154.jpg', upload_to=movies.utils.get_profile_hashed_path, verbose_name='Avatar'),
        ),
    ]
