# Generated by Django 3.0.6 on 2020-06-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='trailer',
        ),
    ]
