# Generated by Django 3.0.6 on 2020-06-04 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_remove_movies_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
