# Generated by Django 3.0.6 on 2020-06-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200604_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.SmallIntegerField(blank=True, choices=[(1, '👍'), (-1, '👍👎')], null=True),
        ),
    ]
