# Generated by Django 3.0.6 on 2020-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200604_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Movie shot', 'verbose_name_plural': 'Movie shots'},
        ),
        migrations.AlterModelOptions(
            name='partnerurls',
            options={'verbose_name': 'Partner url', 'verbose_name_plural': 'Partner urls'},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='slug',
        ),
        migrations.AddField(
            model_name='comments',
            name='file',
            field=models.FileField(blank=True, upload_to='comments/files/<function get_hashed_path at 0x7f17ef062940>'),
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments/images/<function get_hashed_path at 0x7f17ef062940>'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Unique identificator'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Name of category'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date publisher'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='Text comments'),
        ),
        migrations.AlterField(
            model_name='members',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='members',
            name='roles',
            field=models.ManyToManyField(to='movies.Roles', verbose_name='Career'),
        ),
        migrations.AlterField(
            model_name='members',
            name='total_movies',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total movies in which member took part'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='age mark', null=True, verbose_name='Age mark'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='categories',
            field=models.ManyToManyField(to='movies.Categories'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='fees_in_usa',
            field=models.BigIntegerField(blank=True, help_text='indicate the amount in dollars', null=True, verbose_name='Fees in USA'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='fees_in_world',
            field=models.BigIntegerField(blank=True, help_text='indicate the amount in dollars', null=True, verbose_name='Fees in world'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating_imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating IMDB'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating_kp',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating Kinopoisk'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rf_premiere',
            field=models.DateField(blank=True, null=True, verbose_name='Date premier in Russian Federation'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Movie duration'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title movie'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='world_premiere',
            field=models.DateField(blank=True, null=True, verbose_name='World premier'),
        ),
        migrations.AlterField(
            model_name='partnerurls',
            name='name_company',
            field=models.CharField(max_length=255, verbose_name='Name company'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Your rating'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(max_length=150, verbose_name='Career'),
        ),
    ]
