# Generated by Django 3.1b1 on 2020-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200715_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='file',
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments/images/<function get_hashed_path at 0x7fcc1cb5a310>'),
        ),
    ]
