# Generated by Django 3.1b1 on 2020-09-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0010_auto_20200904_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='value',
        ),
        migrations.AddField(
            model_name='likes',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, '👎'), (1, '👍')], null=True, verbose_name='Voice'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments/images/<function get_hashed_path at 0x7f5705d76280>'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
