# Generated by Django 3.1b1 on 2020-09-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20200907_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments/images/<function get_hashed_path at 0x7fe44ca08f70>'),
        ),
    ]
