# Generated by Django 3.1b1 on 2020-09-08 09:45

from django.db import migrations, models
import movies.utils


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20200907_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to=movies.utils.get_comment_hashed_path),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, upload_to=movies.utils.get_member_hashed_path),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, upload_to=movies.utils.get_movie_hashed_path),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to=movies.utils.get_movie_hashed_path),
        ),
    ]
