# Generated by Django 3.1b1 on 2020-09-09 23:44

from django.db import migrations, models
import movies.utils


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20200908_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name of collection')),
                ('image', models.ImageField(blank=True, upload_to=movies.utils.get_movie_hashed_path)),
                ('movies', models.ManyToManyField(blank=True, to='movies.Movies', verbose_name='Movies in collection')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
    ]
